### ISSUE TITLE
Interpolation is not supported in background-image

### ISSUE THREAD

**Issue by rusty-key** [davesnx/styled-ppx#270]
```ml
external logoImage : string = "default" [@@bs.module "./images/logo.svg"]

let logo = [%cx {|
  background-image: url($(logoImage));
|}]
```
↓
```
  13 │ 
  14 │ let logo = [%cx {|
  15 │   background-image: url($(logoImage));
  16 │ |}]
  17 │ 
  
  Unexpected token: ( parsing an URI
```

There is a workaround: 
```ml
external logoImage : string = "default" [@@bs.module "./images/logo.svg"]
let logoImage = `url logoImage

let logo = [%cx {|
  background-image: $(logoImage);
|}]
```

But I wonder if it's possible to make it work when inlining

**Comment by davesnx** [comment]
This isn't possible, since background-image expects `| #BackgroundImage.t | #Url.t | #Gradient.t` and not a string.

One of the possible solutions to these kinds of problems is to allow **any expression** inside interpolation. I believe it can be done, but didn't spike it or studied it yet, and isn't a priority for now.

I'm talking about syntax like this:
```
background-image: $(`url logoImage);
```

I'm closing this issue to keep the issues to 0. Feel free to open another issue or jump into discussions!
